name: epikcoolpackage
description: First dart package not really supposed to be useful
version: 2.0.0
repository: https://github.com/Thepuppetqueen57/epikcoolpackage

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  path: 1.9.1

dev_dependencies:
  lints: 6.0.0
  test: 1.26.2
