name: epikcoolpackage
description: First dart package not really supposed to be useful
version: 1.1.1
repository: https://github.com/Thepuppetqueen57/epikcoolpackage

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
